/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => VaultFileClipboard
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var fs = __toESM(require("fs"));
var path = __toESM(require("path"));
var import_child_process = require("child_process");
var os = __toESM(require("os"));
var import_url = require("url");

// src/lang/locale/en.ts
var en_default = {
  LOAD_PLUGIN: "Loading Vault File Clipboard plugin",
  UNLOAD_PLUGIN: "Unloading Vault File Clipboard plugin",
  COPY_TO_CLIPBOARD: "Vault File Clipboard: copy to clipboard",
  COPY_TO_TARGET_FOLDER: "Vault File Clipboard: copy to target folder",
  PASTE_FROM_CLIPBOARD: "Vault File Clipboard: paste external files here",
  PASTE_NO_FILES: "No external files or folders were found on the system clipboard.",
  PASTE_SUCCESS: "%1 item(s) pasted into %2.",
  PASTE_ERROR: "%1 item(s) could not be pasted.",
  LINKED_FILE: "Linked file ",
  NO_FILES_SELECTED: "No files selected in file explorer.",
  COPY_SUCCESS: "%1 file(s) copied to clipboard.",
  COPY_ERROR_PATHS: "Error: paths could not be determined.",
  COPY_ERROR_GENERIC: "Error during copying. Paths copied as text.",
  CRITICAL_COPY_ERROR: "Critical error during copying.",
  TARGET_FOLDER_SUCCESS: "%1 item(s) copied to target folder.",
  TARGET_FOLDER_ERROR: "%1 error(s) during copying.",
  TARGET_FOLDER_NOT_SET: "Please set a target folder in settings first.",
  SETTINGS_TITLE: "Vault File Clipboard settings",
  SETTING_TARGET_FOLDER_NAME: "Target folder (absolute path)",
  SETTING_TARGET_FOLDER_DESC: "Enter the absolute path to the folder where files should be copied.",
  SETTING_AUDIO_FEEDBACK_NAME: "Audio feedback",
  SETTING_AUDIO_FEEDBACK_DESC: "Play a short sound after a successful copy or paste.",
  SETTING_TEST_SOUND_NAME: "Test sound",
  SETTING_TEST_SOUND_DESC: "Click here to test the audio feedback.",
  SETTING_TEST_SOUND_BUTTON: "Test sound",
  SETTING_CONTEXT_MENU_HEADING: "Context menu",
  SETTING_PASTE_MENU_NAME: "Show paste external files",
  SETTING_PASTE_MENU_DESC: "Show an action on folder context menus that imports files and folders copied in Finder or File Explorer.",
  SETTING_TARGET_FOLDER_MENU_NAME: "Show copy to target folder",
  SETTING_TARGET_FOLDER_MENU_DESC: "Show the copy-to-target-folder action in the file explorer context menu.",
  COPY_COMMAND_NAME: "Copy selected files (from file explorer)",
  SETTING_HELP_NAME: "Documentation and help",
  SETTING_HELP_DESC: "Open the project documentation or report a problem.",
  SETTING_HELP_BUTTON: "Open documentation",
  SETTING_HELP_BUG_BUTTON: "Report bug"
};

// src/lang/locale/de.ts
var de_default = {
  LOAD_PLUGIN: "Lade Vault File Clipboard plugin",
  UNLOAD_PLUGIN: "Entlade Vault File Clipboard plugin",
  COPY_TO_CLIPBOARD: "Vault File Clipboard: in Zwischenablage kopieren",
  COPY_TO_TARGET_FOLDER: "Vault File Clipboard: in Zielordner kopieren",
  LINKED_FILE: "Verlinkte Datei ",
  NO_FILES_SELECTED: "Keine Dateien im File Explorer markiert.",
  COPY_SUCCESS: "%1 Datei(en) in Zwischenablage kopiert.",
  COPY_ERROR_PATHS: "Fehler: Pfade konnten nicht ermittelt werden.",
  COPY_ERROR_GENERIC: "Fehler beim Kopieren. Pfade als Text kopiert.",
  CRITICAL_COPY_ERROR: "Kritischer Fehler beim Kopieren.",
  TARGET_FOLDER_SUCCESS: "%1 Element(e) in Zielordner kopiert.",
  TARGET_FOLDER_ERROR: "%1 Fehler beim Kopieren.",
  TARGET_FOLDER_NOT_SET: "Bitte lege zuerst einen Zielordner in den Einstellungen fest.",
  SETTINGS_TITLE: "Vault File Clipboard Einstellungen",
  SETTING_TARGET_FOLDER_NAME: "Zielordner (Absoluter Pfad)",
  SETTING_TARGET_FOLDER_DESC: "Gib den absoluten Pfad zu dem Ordner an, in den Dateien kopiert werden sollen.",
  SETTING_AUDIO_FEEDBACK_NAME: "Audio-Feedback",
  SETTING_AUDIO_FEEDBACK_DESC: "Spielt einen kurzen Sound ab, wenn eine Datei erfolgreich kopiert wurde.",
  SETTING_TEST_SOUND_NAME: "Sound testen",
  SETTING_TEST_SOUND_DESC: "Klicke hier, um das Audio-Feedback zu testen.",
  SETTING_TEST_SOUND_BUTTON: "Test Sound",
  COPY_COMMAND_NAME: "Kopiere markierte Dateien (aus dem File Explorer)",
  SETTING_HELP_NAME: "Dokumentation und Hilfe",
  SETTING_HELP_DESC: "\xD6ffne die Projektdokumentation.",
  SETTING_HELP_BUTTON: "Dokumentation \xF6ffnen",
  SETTING_HELP_BUG_BUTTON: "Fehler melden"
};

// src/lang/locale/fr.ts
var fr_default = {
  LOAD_PLUGIN: "Chargement du plugin Vault File Clipboard",
  UNLOAD_PLUGIN: "D\xE9chargement du plugin Vault File Clipboard",
  COPY_TO_CLIPBOARD: "Vault File Clipboard : copier dans le presse-papiers",
  COPY_TO_TARGET_FOLDER: "Vault File Clipboard : copier dans le dossier cible",
  LINKED_FILE: "Fichier li\xE9 ",
  NO_FILES_SELECTED: "Aucun fichier s\xE9lectionn\xE9 dans l'explorateur de fichiers.",
  COPY_SUCCESS: "%1 fichier(s) copi\xE9(s) dans le presse-papiers.",
  COPY_ERROR_PATHS: "Erreur : les chemins n'ont pas pu \xEAtre d\xE9termin\xE9s.",
  COPY_ERROR_GENERIC: "Erreur lors de la copie. Chemins copi\xE9s en tant que texte.",
  CRITICAL_COPY_ERROR: "Erreur critique lors de la copie.",
  TARGET_FOLDER_SUCCESS: "%1 \xE9l\xE9ment(s) copi\xE9(s) dans le dossier cible.",
  TARGET_FOLDER_ERROR: "%1 erreur(s) lors de la copie.",
  TARGET_FOLDER_NOT_SET: "Veuillez d'abord d\xE9finir un dossier cible dans les param\xE8tres.",
  SETTINGS_TITLE: "Param\xE8tres de Vault File Clipboard",
  SETTING_TARGET_FOLDER_NAME: "Dossier cible (chemin absolu)",
  SETTING_TARGET_FOLDER_DESC: "Entrez le chemin absolu du dossier o\xF9 les fichiers doivent \xEAtre copi\xE9s.",
  SETTING_AUDIO_FEEDBACK_NAME: "Retour audio",
  SETTING_AUDIO_FEEDBACK_DESC: "Joue un court son lorsqu'un fichier est copi\xE9 avec succ\xE8s.",
  SETTING_TEST_SOUND_NAME: "Tester le son",
  SETTING_TEST_SOUND_DESC: "Cliquez ici pour tester le retour audio.",
  SETTING_TEST_SOUND_BUTTON: "Tester le son",
  COPY_COMMAND_NAME: "Copier les fichiers s\xE9lectionn\xE9s (depuis l'explorateur de fichiers)",
  SETTING_HELP_NAME: "Documentation et aide",
  SETTING_HELP_DESC: "Ouvrir la documentation du projet.",
  SETTING_HELP_BUTTON: "Ouvrir la documentation",
  SETTING_HELP_BUG_BUTTON: "Signaler un bug"
};

// src/lang/locale/es.ts
var es_default = {
  LOAD_PLUGIN: "Cargando el complemento Vault File Clipboard",
  UNLOAD_PLUGIN: "Descargando el complemento Vault File Clipboard",
  COPY_TO_CLIPBOARD: "Vault File Clipboard: copiar al portapapeles",
  COPY_TO_TARGET_FOLDER: "Vault File Clipboard: copiar a la carpeta de destino",
  LINKED_FILE: "Archivo vinculado ",
  NO_FILES_SELECTED: "No hay archivos seleccionados en el explorador de archivos.",
  COPY_SUCCESS: "%1 archivo(s) copiado(s) al portapapeles.",
  COPY_ERROR_PATHS: "Error: no se pudieron determinar las rutas.",
  COPY_ERROR_GENERIC: "Error durante la copia. Rutas copiadas como texto.",
  CRITICAL_COPY_ERROR: "Error cr\xEDtico durante la copia.",
  TARGET_FOLDER_SUCCESS: "%1 elemento(s) copiado(s) a la carpeta de destino.",
  TARGET_FOLDER_ERROR: "%1 error(es) durante la copia.",
  TARGET_FOLDER_NOT_SET: "Primero establezca una carpeta de destino en la configuraci\xF3n.",
  SETTINGS_TITLE: "Configuraci\xF3n de Vault File Clipboard",
  SETTING_TARGET_FOLDER_NAME: "Carpeta de destino (ruta absoluta)",
  SETTING_TARGET_FOLDER_DESC: "Ingrese la ruta absoluta de la carpeta donde se deben copiar los archivos.",
  SETTING_AUDIO_FEEDBACK_NAME: "Retroalimentaci\xF3n de audio",
  SETTING_AUDIO_FEEDBACK_DESC: "Reproduce un sonido corto cuando un archivo se copia con \xE9xito.",
  SETTING_TEST_SOUND_NAME: "Probar sonido",
  SETTING_TEST_SOUND_DESC: "Haga clic aqu\xED para probar la retroalimentaci\xF3n de audio.",
  SETTING_TEST_SOUND_BUTTON: "Probar sonido",
  COPY_COMMAND_NAME: "Copiar archivos seleccionados (desde el explorador de archivos)",
  SETTING_HELP_NAME: "Documentaci\xF3n y ayuda",
  SETTING_HELP_DESC: "Abre la documentaci\xF3n del proyecto.",
  SETTING_HELP_BUTTON: "Abrir documentaci\xF3n",
  SETTING_HELP_BUG_BUTTON: "Reportar error"
};

// src/lang/locale/zh.ts
var zh_default = {
  LOAD_PLUGIN: "\u6B63\u5728\u52A0\u8F7D Vault File Clipboard \u63D2\u4EF6",
  UNLOAD_PLUGIN: "\u6B63\u5728\u5378\u8F7D Vault File Clipboard \u63D2\u4EF6",
  COPY_TO_CLIPBOARD: "Vault File Clipboard: \u590D\u5236\u5230\u526A\u8D34\u677F",
  COPY_TO_TARGET_FOLDER: "Vault File Clipboard: \u590D\u5236\u5230\u76EE\u6807\u6587\u4EF6\u5939",
  PASTE_FROM_CLIPBOARD: "Vault File Clipboard: \u7C98\u8D34\u5916\u90E8\u6587\u4EF6\u5230\u6B64\u5904",
  PASTE_NO_FILES: "\u7CFB\u7EDF\u526A\u8D34\u677F\u4E2D\u6CA1\u6709\u53EF\u7C98\u8D34\u7684\u5916\u90E8\u6587\u4EF6\u6216\u6587\u4EF6\u5939\u3002",
  PASTE_SUCCESS: "\u5DF2\u5C06 %1 \u4E2A\u9879\u76EE\u7C98\u8D34\u5230 %2\u3002",
  PASTE_ERROR: "%1 \u4E2A\u9879\u76EE\u7C98\u8D34\u5931\u8D25\u3002",
  LINKED_FILE: "\u94FE\u63A5\u6587\u4EF6 ",
  NO_FILES_SELECTED: "\u6587\u4EF6\u8D44\u6E90\u7BA1\u7406\u5668\u4E2D\u672A\u9009\u62E9\u6587\u4EF6\u3002",
  COPY_SUCCESS: "\u5DF2\u5C06 %1 \u4E2A\u6587\u4EF6\u590D\u5236\u5230\u526A\u8D34\u677F\u3002",
  COPY_ERROR_PATHS: "\u9519\u8BEF\uFF1A\u65E0\u6CD5\u786E\u5B9A\u8DEF\u5F84\u3002",
  COPY_ERROR_GENERIC: "\u590D\u5236\u8FC7\u7A0B\u4E2D\u51FA\u9519\u3002\u8DEF\u5F84\u5DF2\u4F5C\u4E3A\u6587\u672C\u590D\u5236\u3002",
  CRITICAL_COPY_ERROR: "\u590D\u5236\u8FC7\u7A0B\u4E2D\u53D1\u751F\u4E25\u91CD\u9519\u8BEF\u3002",
  TARGET_FOLDER_SUCCESS: "\u5DF2\u5C06 %1 \u4E2A\u9879\u76EE\u590D\u5236\u5230\u76EE\u6807\u6587\u4EF6\u5939\u3002",
  TARGET_FOLDER_ERROR: "\u590D\u5236\u8FC7\u7A0B\u4E2D\u51FA\u73B0 %1 \u4E2A\u9519\u8BEF\u3002",
  TARGET_FOLDER_NOT_SET: "\u8BF7\u5148\u5728\u8BBE\u7F6E\u4E2D\u8BBE\u7F6E\u76EE\u6807\u6587\u4EF6\u5939\u3002",
  SETTINGS_TITLE: "Vault File Clipboard \u8BBE\u7F6E",
  SETTING_TARGET_FOLDER_NAME: "\u76EE\u6807\u6587\u4EF6\u5939\uFF08\u7EDD\u5BF9\u8DEF\u5F84\uFF09",
  SETTING_TARGET_FOLDER_DESC: "\u8F93\u5165\u8981\u5C06\u6587\u4EF6\u590D\u5236\u5230\u7684\u6587\u4EF6\u5939\u7EDD\u5BF9\u8DEF\u5F84\u3002",
  SETTING_AUDIO_FEEDBACK_NAME: "\u97F3\u9891\u53CD\u9988",
  SETTING_AUDIO_FEEDBACK_DESC: "\u6210\u529F\u590D\u5236\u6216\u7C98\u8D34\u540E\u64AD\u653E\u77ED\u4FC3\u7684\u58F0\u97F3\u3002",
  SETTING_TEST_SOUND_NAME: "\u6D4B\u8BD5\u58F0\u97F3",
  SETTING_TEST_SOUND_DESC: "\u70B9\u51FB\u6B64\u5904\u6D4B\u8BD5\u97F3\u9891\u53CD\u9988\u3002",
  SETTING_TEST_SOUND_BUTTON: "\u6D4B\u8BD5\u58F0\u97F3",
  SETTING_CONTEXT_MENU_HEADING: "\u53F3\u952E\u83DC\u5355",
  SETTING_PASTE_MENU_NAME: "\u663E\u793A\u201C\u7C98\u8D34\u5916\u90E8\u6587\u4EF6\u201D",
  SETTING_PASTE_MENU_DESC: "\u5728\u6587\u4EF6\u5939\u53F3\u952E\u83DC\u5355\u4E2D\u663E\u793A\u5BFC\u5165\u529F\u80FD\uFF0C\u53EF\u7C98\u8D34\u4ECE\u8BBF\u8FBE\u6216\u6587\u4EF6\u8D44\u6E90\u7BA1\u7406\u5668\u590D\u5236\u7684\u6587\u4EF6\u548C\u6587\u4EF6\u5939\u3002",
  SETTING_TARGET_FOLDER_MENU_NAME: "\u663E\u793A\u201C\u590D\u5236\u5230\u76EE\u6807\u6587\u4EF6\u5939\u201D",
  SETTING_TARGET_FOLDER_MENU_DESC: "\u5728\u6587\u4EF6\u8D44\u6E90\u7BA1\u7406\u5668\u53F3\u952E\u83DC\u5355\u4E2D\u663E\u793A\u590D\u5236\u5230\u76EE\u6807\u6587\u4EF6\u5939\u529F\u80FD\u3002",
  COPY_COMMAND_NAME: "\u590D\u5236\u6240\u9009\u6587\u4EF6\uFF08\u4ECE\u6587\u4EF6\u8D44\u6E90\u7BA1\u7406\u5668\uFF09",
  SETTING_HELP_NAME: "\u6587\u6863\u4E0E\u5E2E\u52A9",
  SETTING_HELP_DESC: "\u6253\u5F00\u9879\u76EE\u6587\u6863\u6216\u62A5\u544A\u95EE\u9898\u3002",
  SETTING_HELP_BUTTON: "\u6253\u5F00\u6587\u6863",
  SETTING_HELP_BUG_BUTTON: "\u62A5\u544A\u9519\u8BEF"
};

// src/lang/locale/ja.ts
var ja_default = {
  LOAD_PLUGIN: "Vault File Clipboard \u30D7\u30E9\u30B0\u30A4\u30F3\u3092\u8AAD\u307F\u8FBC\u3093\u3067\u3044\u307E\u3059",
  UNLOAD_PLUGIN: "Vault File Clipboard \u30D7\u30E9\u30B0\u30A4\u30F3\u3092\u89E3\u9664\u3057\u3066\u3044\u307E\u3059",
  COPY_TO_CLIPBOARD: "Vault File Clipboard: \u30AF\u30EA\u30C3\u30D7\u30DC\u30FC\u30C9\u306B\u30B3\u30D4\u30FC",
  COPY_TO_TARGET_FOLDER: "Vault File Clipboard: \u30BF\u30FC\u30B2\u30C3\u30C8\u30D5\u30A9\u30EB\u30C0\u306B\u30B3\u30D4\u30FC",
  LINKED_FILE: "\u30EA\u30F3\u30AF\u3055\u308C\u305F\u30D5\u30A1\u30A4\u30EB ",
  NO_FILES_SELECTED: "\u30D5\u30A1\u30A4\u30EB\u30A8\u30AF\u30B9\u30D7\u30ED\u30FC\u30E9\u30FC\u3067\u30D5\u30A1\u30A4\u30EB\u304C\u9078\u629E\u3055\u308C\u3066\u3044\u307E\u305B\u3093\u3002",
  COPY_SUCCESS: "%1 \u500B\u306E\u30D5\u30A1\u30A4\u30EB\u3092\u30AF\u30EA\u30C3\u30D7\u30DC\u30FC\u30C9\u306B\u30B3\u30D4\u30FC\u3057\u307E\u3057\u305F\u3002",
  COPY_ERROR_PATHS: "\u30A8\u30E9\u30FC: \u30D1\u30B9\u3092\u7279\u5B9A\u3067\u304D\u307E\u305B\u3093\u3067\u3057\u305F\u3002",
  COPY_ERROR_GENERIC: "\u30B3\u30D4\u30FC\u4E2D\u306B\u30A8\u30E9\u30FC\u304C\u767A\u751F\u3057\u307E\u3057\u305F\u3002\u30D1\u30B9\u3092\u30C6\u30AD\u30B9\u30C8\u3068\u3057\u3066\u30B3\u30D4\u30FC\u3057\u307E\u3057\u305F\u3002",
  CRITICAL_COPY_ERROR: "\u30B3\u30D4\u30FC\u4E2D\u306B\u81F4\u547D\u7684\u306A\u30A8\u30E9\u30FC\u304C\u767A\u751F\u3057\u307E\u3057\u305F\u3002",
  TARGET_FOLDER_SUCCESS: "%1 \u500B\u306E\u30A2\u30A4\u30C6\u30E0\u3092\u30BF\u30FC\u30B2\u30C3\u30C8\u30D5\u30A9\u30EB\u30C0\u306B\u30B3\u30D4\u30FC\u3057\u307E\u3057\u305F\u3002",
  TARGET_FOLDER_ERROR: "\u30B3\u30D4\u30FC\u4E2D\u306B %1 \u500B\u306E\u30A8\u30E9\u30FC\u304C\u767A\u751F\u3057\u307E\u3057\u305F\u3002",
  TARGET_FOLDER_NOT_SET: "\u6700\u521D\u306B\u8A2D\u5B9A\u3067\u30BF\u30FC\u30B2\u30C3\u30C8\u30D5\u30A9\u30EB\u30C0\u3092\u6307\u5B9A\u3057\u3066\u304F\u3060\u3055\u3044\u3002",
  SETTINGS_TITLE: "Vault File Clipboard \u8A2D\u5B9A",
  SETTING_TARGET_FOLDER_NAME: "\u30BF\u30FC\u30B2\u30C3\u30C8\u30D5\u30A9\u30EB\u30C0 (\u7D76\u5BFE\u30D1\u30B9)",
  SETTING_TARGET_FOLDER_DESC: "\u30D5\u30A1\u30A4\u30EB\u3092\u30B3\u30D4\u30FC\u3059\u308B\u30D5\u30A9\u30EB\u30C0\u306E\u7D76\u5BFE\u30D1\u30B9\u3092\u5165\u529B\u3057\u3066\u304F\u3060\u3055\u3044\u3002",
  SETTING_AUDIO_FEEDBACK_NAME: "\u30AA\u30FC\u30C7\u30A3\u30AA\u30D5\u30A3\u30FC\u30C9\u30D0\u30C3\u30AF",
  SETTING_AUDIO_FEEDBACK_DESC: "\u30D5\u30A1\u30A4\u30EB\u306E\u30B3\u30D4\u30FC\u306B\u6210\u529F\u3057\u305F\u3068\u304D\u306B\u77ED\u3044\u97F3\u3092\u518D\u751F\u3057\u307E\u3059\u3002",
  SETTING_TEST_SOUND_NAME: "\u30B5\u30A6\u30F3\u30C9\u30C6\u30B9\u30C8",
  SETTING_TEST_SOUND_DESC: "\u3053\u3053\u3092\u30AF\u30EA\u30C3\u30AF\u3057\u3066\u30AA\u30FC\u30C7\u30A3\u30AA\u30D5\u30A3\u30FC\u30C9\u30D0\u30C3\u30AF\u3092\u30C6\u30B9\u30C8\u3057\u307E\u3059\u3002",
  SETTING_TEST_SOUND_BUTTON: "\u30B5\u30A6\u30F3\u30C9\u30C6\u30B9\u30C8",
  COPY_COMMAND_NAME: "\u9078\u629E\u3057\u305F\u30D5\u30A1\u30A4\u30EB\u3092\u30B3\u30D4\u30FC (\u30D5\u30A1\u30A4\u30EB\u30A8\u30AF\u30B9\u30D7\u30ED\u30FC\u30E9\u30FC\u304B\u3089)",
  SETTING_HELP_NAME: "\u30C9\u30AD\u30E5\u30E1\u30F3\u30C8\u3068\u30D8\u30EB\u30D7",
  SETTING_HELP_DESC: "\u30D7\u30ED\u30B8\u30A7\u30AF\u30C8\u306E\u30C9\u30AD\u30E5\u30E1\u30F3\u30C8\u3092\u958B\u304D\u307E\u3059\u3002",
  SETTING_HELP_BUTTON: "\u30C9\u30AD\u30E5\u30E1\u30F3\u30C8\u3092\u958B\u304F",
  SETTING_HELP_BUG_BUTTON: "\u30D0\u30B0\u3092\u5831\u544A"
};

// src/lang/locale/ko.ts
var ko_default = {
  LOAD_PLUGIN: "Vault File Clipboard \uD50C\uB7EC\uADF8\uC778\uC744 \uBD88\uB7EC\uC624\uB294 \uC911",
  UNLOAD_PLUGIN: "Vault File Clipboard \uD50C\uB7EC\uADF8\uC778\uC744 \uD574\uC81C\uD558\uB294 \uC911",
  COPY_TO_CLIPBOARD: "Vault File Clipboard: \uD074\uB9BD\uBCF4\uB4DC\uC5D0 \uBCF5\uC0AC",
  COPY_TO_TARGET_FOLDER: "Vault File Clipboard: \uB300\uC0C1 \uD3F4\uB354\uB85C \uBCF5\uC0AC",
  LINKED_FILE: "\uC5F0\uACB0\uB41C \uD30C\uC77C ",
  NO_FILES_SELECTED: "\uD30C\uC77C \uD0D0\uC0C9\uAE30\uC5D0\uC11C \uC120\uD0DD\uB41C \uD30C\uC77C\uC774 \uC5C6\uC2B5\uB2C8\uB2E4.",
  COPY_SUCCESS: "%1\uAC1C\uC758 \uD30C\uC77C\uC744 \uD074\uB9BD\uBCF4\uB4DC\uC5D0 \uBCF5\uC0AC\uD588\uC2B5\uB2C8\uB2E4.",
  COPY_ERROR_PATHS: "\uC624\uB958: \uACBD\uB85C\uB97C \uD655\uC778\uD560 \uC218 \uC5C6\uC2B5\uB2C8\uB2E4.",
  COPY_ERROR_GENERIC: "\uBCF5\uC0AC \uC911 \uC624\uB958\uAC00 \uBC1C\uC0DD\uD588\uC2B5\uB2C8\uB2E4. \uACBD\uB85C\uB97C \uD14D\uC2A4\uD2B8\uB85C \uBCF5\uC0AC\uD588\uC2B5\uB2C8\uB2E4.",
  CRITICAL_COPY_ERROR: "\uBCF5\uC0AC \uC911 \uCE58\uBA85\uC801\uC778 \uC624\uB958\uAC00 \uBC1C\uC0DD\uD588\uC2B5\uB2C8\uB2E4.",
  TARGET_FOLDER_SUCCESS: "%1\uAC1C\uC758 \uD56D\uBAA9\uC744 \uB300\uC0C1 \uD3F4\uB354\uB85C \uBCF5\uC0AC\uD588\uC2B5\uB2C8\uB2E4.",
  TARGET_FOLDER_ERROR: "\uBCF5\uC0AC \uC911 %1\uAC1C\uC758 \uC624\uB958\uAC00 \uBC1C\uC0DD\uD588\uC2B5\uB2C8\uB2E4.",
  TARGET_FOLDER_NOT_SET: "\uBA3C\uC800 \uC124\uC815\uC5D0\uC11C \uB300\uC0C1 \uD3F4\uB354\uB97C \uC9C0\uC815\uD558\uC2ED\uC2DC\uC624.",
  SETTINGS_TITLE: "Vault File Clipboard \uC124\uC815",
  SETTING_TARGET_FOLDER_NAME: "\uB300\uC0C1 \uD3F4\uB354 (\uC808\uB300 \uACBD\uB85C)",
  SETTING_TARGET_FOLDER_DESC: "\uD30C\uC77C\uC744 \uBCF5\uC0AC\uD560 \uD3F4\uB354\uC758 \uC808\uB300 \uACBD\uB85C\uB97C \uC785\uB825\uD558\uC2ED\uC2DC\uC624.",
  SETTING_AUDIO_FEEDBACK_NAME: "\uC624\uB514\uC624 \uD53C\uB4DC\uBC31",
  SETTING_AUDIO_FEEDBACK_DESC: "\uD30C\uC77C \uBCF5\uC0AC \uC131\uACF5 \uC2DC \uC9E7\uC740 \uD6A8\uACFC\uC74C\uC744 \uC7AC\uC0DD\uD569\uB2C8\uB2E4.",
  SETTING_TEST_SOUND_NAME: "\uC0AC\uC6B4\uB4DC \uD14C\uC2A4\uD2B8",
  SETTING_TEST_SOUND_DESC: "\uC5EC\uAE30\uB97C \uD074\uB9AD\uD558\uC5EC \uC624\uB514\uC624 \uD53C\uB4DC\uBC31\uC744 \uD14C\uC2A4\uD2B8\uD558\uC2ED\uC2DC\uC624.",
  SETTING_TEST_SOUND_BUTTON: "\uC0AC\uC6B4\uB4DC \uD14C\uC2A4\uD2B8",
  COPY_COMMAND_NAME: "\uC120\uD0DD\uD55C \uD30C\uC77C \uBCF5\uC0AC (\uD30C\uC77C \uD0D0\uC0C9\uAE30\uC5D0\uC11C)",
  SETTING_HELP_NAME: "\uBB38\uC11C \uBC0F \uB3C4\uC6C0\uB9D0",
  SETTING_HELP_DESC: "\uD504\uB85C\uC81D\uD2B8 \uBB38\uC11C\uB97C \uC5FD\uB2C8\uB2E4.",
  SETTING_HELP_BUTTON: "\uBB38\uC11C \uC5F4\uAE30",
  SETTING_HELP_BUG_BUTTON: "\uBC84\uADF8 \uC2E0\uACE0"
};

// src/lang/locale/pt.ts
var pt_default = {
  LOAD_PLUGIN: "Carregando o plugin Vault File Clipboard",
  UNLOAD_PLUGIN: "Descarregando o plugin Vault File Clipboard",
  COPY_TO_CLIPBOARD: "Vault File Clipboard: copiar para a \xE1rea de transfer\xEAncia",
  COPY_TO_TARGET_FOLDER: "Vault File Clipboard: copiar para a pasta de destino",
  LINKED_FILE: "Arquivo vinculado ",
  NO_FILES_SELECTED: "Nenhum arquivo selecionado no explorador de arquivos.",
  COPY_SUCCESS: "%1 arquivo(s) copiado(s) para a \xE1rea de transfer\xEAncia.",
  COPY_ERROR_PATHS: "Erro: os caminhos n\xE3o puderam ser determinados.",
  COPY_ERROR_GENERIC: "Erro durante a c\xF3pia. Caminhos copiados como texto.",
  CRITICAL_COPY_ERROR: "Erro cr\xEDtico durante a c\xF3pia.",
  TARGET_FOLDER_SUCCESS: "%1 item(ns) copiado(s) para a pasta de destino.",
  TARGET_FOLDER_ERROR: "%1 erro(s) durante a c\xF3pia.",
  TARGET_FOLDER_NOT_SET: "Por favor, defina uma pasta de destino nas configura\xE7\xF5es primeiro.",
  SETTINGS_TITLE: "Configura\xE7\xF5es do Vault File Clipboard",
  SETTING_TARGET_FOLDER_NAME: "Pasta de destino (caminho absoluto)",
  SETTING_TARGET_FOLDER_DESC: "Insira o caminho absoluto da pasta para onde os arquivos devem ser copiados.",
  SETTING_AUDIO_FEEDBACK_NAME: "Feedback de \xE1udio",
  SETTING_AUDIO_FEEDBACK_DESC: "Reproduz um som curto quando um arquivo \xE9 copiado com sucesso.",
  SETTING_TEST_SOUND_NAME: "Testar som",
  SETTING_TEST_SOUND_DESC: "Clique aqui para testar o feedback de \xE1udio.",
  SETTING_TEST_SOUND_BUTTON: "Testar som",
  COPY_COMMAND_NAME: "Copiar arquivos selecionados (do explorador de arquivos)",
  SETTING_HELP_NAME: "Documenta\xE7\xE3o e ajuda",
  SETTING_HELP_DESC: "Abra a documenta\xE7\xE3o do projeto.",
  SETTING_HELP_BUTTON: "Abrir documenta\xE7\xE3o",
  SETTING_HELP_BUG_BUTTON: "Relatar erro"
};

// src/lang/locale/ru.ts
var ru_default = {
  LOAD_PLUGIN: "\u0417\u0430\u0433\u0440\u0443\u0437\u043A\u0430 \u043F\u043B\u0430\u0433\u0438\u043D\u0430 Vault File Clipboard",
  UNLOAD_PLUGIN: "\u0412\u044B\u0433\u0440\u0443\u0437\u043A\u0430 \u043F\u043B\u0430\u0433\u0438\u043D\u0430 Vault File Clipboard",
  COPY_TO_CLIPBOARD: "Vault File Clipboard: \u043A\u043E\u043F\u0438\u0440\u043E\u0432\u0430\u0442\u044C \u0432 \u0431\u0443\u0444\u0435\u0440 \u043E\u0431\u043C\u0435\u043D\u0430",
  COPY_TO_TARGET_FOLDER: "Vault File Clipboard: \u043A\u043E\u043F\u0438\u0440\u043E\u0432\u0430\u0442\u044C \u0432 \u0446\u0435\u043B\u0435\u0432\u0443\u044E \u043F\u0430\u043F\u043A\u0443",
  LINKED_FILE: "\u0421\u0432\u044F\u0437\u0430\u043D\u043D\u044B\u0439 \u0444\u0430\u0439\u043B ",
  NO_FILES_SELECTED: "\u0424\u0430\u0439\u043B\u044B \u0432 \u043F\u0440\u043E\u0432\u043E\u0434\u043D\u0438\u043A\u0435 \u043D\u0435 \u0432\u044B\u0431\u0440\u0430\u043D\u044B.",
  COPY_SUCCESS: "\u0424\u0430\u0439\u043B\u043E\u0432 \u0441\u043A\u043E\u043F\u0438\u0440\u043E\u0432\u0430\u043D\u043E \u0432 \u0431\u0443\u0444\u0435\u0440 \u043E\u0431\u043C\u0435\u043D\u0430: %1.",
  COPY_ERROR_PATHS: "\u041E\u0448\u0438\u0431\u043A\u0430: \u043D\u0435 \u0443\u0434\u0430\u043B\u043E\u0441\u044C \u043E\u043F\u0440\u0435\u0434\u0435\u043B\u0438\u0442\u044C \u043F\u0443\u0442\u0438.",
  COPY_ERROR_GENERIC: "\u041E\u0448\u0438\u0431\u043A\u0430 \u043F\u0440\u0438 \u043A\u043E\u043F\u0438\u0440\u043E\u0432\u0430\u043D\u0438\u0438. \u041F\u0443\u0442\u0438 \u0441\u043A\u043E\u043F\u0438\u0440\u043E\u0432\u0430\u043D\u044B \u043A\u0430\u043A \u0442\u0435\u043A\u0441\u0442.",
  CRITICAL_COPY_ERROR: "\u041A\u0440\u0438\u0442\u0438\u0447\u0435\u0441\u043A\u0430\u044F \u043E\u0448\u0438\u0431\u043A\u0430 \u043F\u0440\u0438 \u043A\u043E\u043F\u0438\u0440\u043E\u0432\u0430\u043D\u0438\u0438.",
  TARGET_FOLDER_SUCCESS: "\u042D\u043B\u0435\u043C\u0435\u043D\u0442\u043E\u0432 \u0441\u043A\u043E\u043F\u0438\u0440\u043E\u0432\u0430\u043D\u043E \u0432 \u0446\u0435\u043B\u0435\u0432\u0443\u044E \u043F\u0430\u043F\u043A\u0443: %1.",
  TARGET_FOLDER_ERROR: "\u041E\u0448\u0438\u0431\u043E\u043A \u043F\u0440\u0438 \u043A\u043E\u043F\u0438\u0440\u043E\u0432\u0430\u043D\u0438\u0438: %1.",
  TARGET_FOLDER_NOT_SET: "\u0421\u043D\u0430\u0447\u0430\u043B\u0430 \u0443\u043A\u0430\u0436\u0438\u0442\u0435 \u0446\u0435\u043B\u0435\u0432\u0443\u044E \u043F\u0430\u043F\u043A\u0443 \u0432 \u043D\u0430\u0441\u0442\u0440\u043E\u0439\u043A\u0430\u0445.",
  SETTINGS_TITLE: "\u041D\u0430\u0441\u0442\u0440\u043E\u0439\u043A\u0438 Vault File Clipboard",
  SETTING_TARGET_FOLDER_NAME: "\u0426\u0435\u043B\u0435\u0432\u0430\u044F \u043F\u0430\u043F\u043A\u0430 (\u0430\u0431\u0441\u043E\u043B\u044E\u0442\u043D\u044B\u0439 \u043F\u0443\u0442\u044C)",
  SETTING_TARGET_FOLDER_DESC: "\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u0430\u0431\u0441\u043E\u043B\u044E\u0442\u043D\u044B\u0439 \u043F\u0443\u0442\u044C \u043A \u043F\u0430\u043F\u043A\u0435, \u0432 \u043A\u043E\u0442\u043E\u0440\u0443\u044E \u0434\u043E\u043B\u0436\u043D\u044B \u043A\u043E\u043F\u0438\u0440\u043E\u0432\u0430\u0442\u044C\u0441\u044F \u0444\u0430\u0439\u043B\u044B.",
  SETTING_AUDIO_FEEDBACK_NAME: "\u0417\u0432\u0443\u043A\u043E\u0432\u043E\u0439 \u043E\u0442\u043A\u043B\u0438\u043A",
  SETTING_AUDIO_FEEDBACK_DESC: "\u0412\u043E\u0441\u043F\u0440\u043E\u0438\u0437\u0432\u043E\u0434\u0438\u0442\u044C \u043A\u043E\u0440\u043E\u0442\u043A\u0438\u0439 \u0437\u0432\u0443\u043A \u043F\u0440\u0438 \u0443\u0441\u043F\u0435\u0448\u043D\u043E\u043C \u043A\u043E\u043F\u0438\u0440\u043E\u0432\u0430\u043D\u0438\u0438 \u0444\u0430\u0439\u043B\u0430.",
  SETTING_TEST_SOUND_NAME: "\u041F\u0440\u043E\u0432\u0435\u0440\u0438\u0442\u044C \u0437\u0432\u0443\u043A",
  SETTING_TEST_SOUND_DESC: "\u041D\u0430\u0436\u043C\u0438\u0442\u0435 \u0437\u0434\u0435\u0441\u044C, \u0447\u0442\u043E\u0431\u044B \u043F\u0440\u043E\u0432\u0435\u0440\u0438\u0442\u044C \u0437\u0432\u0443\u043A\u043E\u0432\u043E\u0439 \u043E\u0442\u043A\u043B\u0438\u043A.",
  SETTING_TEST_SOUND_BUTTON: "\u041F\u0440\u043E\u0432\u0435\u0440\u0438\u0442\u044C \u0437\u0432\u0443\u043A",
  COPY_COMMAND_NAME: "\u041A\u043E\u043F\u0438\u0440\u043E\u0432\u0430\u0442\u044C \u0432\u044B\u0431\u0440\u0430\u043D\u043D\u044B\u0435 \u0444\u0430\u0439\u043B\u044B (\u0438\u0437 \u043F\u0440\u043E\u0432\u043E\u0434\u043D\u0438\u043A\u0430)",
  SETTING_HELP_NAME: "\u0414\u043E\u043A\u0443\u043C\u0435\u043D\u0442\u0430\u0446\u0438\u044F \u0438 \u043F\u043E\u043C\u043E\u0449\u044C",
  SETTING_HELP_DESC: "\u041E\u0442\u043A\u0440\u044B\u0442\u044C \u0434\u043E\u043A\u0443\u043C\u0435\u043D\u0442\u0430\u0446\u0438\u044E \u043F\u0440\u043E\u0435\u043A\u0442\u0430.",
  SETTING_HELP_BUTTON: "\u041E\u0442\u043A\u0440\u044B\u0442\u044C \u0434\u043E\u043A\u0443\u043C\u0435\u043D\u0442\u0430\u0446\u0438\u044E",
  SETTING_HELP_BUG_BUTTON: "\u0421\u043E\u043E\u0431\u0449\u0438\u0442\u044C \u043E\u0431 \u043E\u0448\u0438\u0431\u043A\u0435"
};

// src/lang/helpers.ts
var localeMap = {
  en: en_default,
  de: de_default,
  fr: fr_default,
  es: es_default,
  zh: zh_default,
  "zh-cn": zh_default,
  ja: ja_default,
  ko: ko_default,
  pt: pt_default,
  "pt-br": pt_default,
  ru: ru_default
};
function t(str, ...args) {
  const currentLang = window.localStorage.getItem("language") || "en";
  const locale = localeMap[currentLang] || en_default;
  let text = locale[str] || en_default[str] || str;
  if (args && args.length > 0) {
    args.forEach((arg, i) => {
      text = text.replace(`%${i + 1}`, arg);
    });
  }
  return text;
}

// src/main.ts
var electron = __toESM(require("electron"));
var { clipboard } = electron;
var DEFAULT_SETTINGS = {
  targetFolderPath: "",
  enableAudioFeedback: true,
  showPasteFromClipboardMenu: true,
  showCopyToTargetFolderMenu: true
};
var VaultFileClipboard = class extends import_obsidian.Plugin {
  settings;
  audioCtx = null;
  boundDragStartHandler;
  boundKeyDownHandler;
  async onload() {
    console.debug(t("LOAD_PLUGIN"));
    await this.loadSettings();
    this.initAudio();
    this.boundKeyDownHandler = (evt) => {
      if (!(evt.metaKey || evt.ctrlKey) || evt.altKey) return;
      const isCopyShortcut = evt.key.toLowerCase() === "c" || evt.code === "KeyC";
      const isPasteShortcut = !evt.shiftKey && (evt.key.toLowerCase() === "v" || evt.code === "KeyV");
      if (!isCopyShortcut && !isPasteShortcut) return;
      const target = evt.target instanceof HTMLElement ? evt.target : null;
      if (target && (target.tagName === "INPUT" || target.tagName === "TEXTAREA" || target.isContentEditable || target.closest(".cm-editor, .markdown-source-view, .markdown-rendered"))) {
        return;
      }
      if (isCopyShortcut) {
        const files = this.getSelectedFiles();
        if (files.length > 0) {
          evt.preventDefault();
          evt.stopPropagation();
          void this.copyFilesToClipboard(files);
        }
        return;
      }
      if (evt.repeat) return;
      const targetFolder = this.getSelectedFolderForPaste(target);
      if (targetFolder) {
        evt.preventDefault();
        evt.stopImmediatePropagation();
        void this.pasteExternalFiles(targetFolder);
      }
    };
    document.addEventListener("keydown", this.boundKeyDownHandler, true);
    this.addCommand({
      id: "copy-selected-files",
      name: t("COPY_COMMAND_NAME"),
      callback: () => {
        const files = this.getSelectedFiles();
        if (files.length > 0) {
          void this.copyFilesToClipboard(files);
        } else {
          new import_obsidian.Notice(t("NO_FILES_SELECTED"));
        }
      }
    });
    this.boundDragStartHandler = this.handleDragStart.bind(this);
    document.addEventListener("dragstart", this.boundDragStartHandler, true);
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        if (file instanceof import_obsidian.TAbstractFile) {
          this.addCopyMenuItems(menu, [file], false);
        }
      })
    );
    this.registerEvent(
      this.app.workspace.on("files-menu", (menu, files) => {
        if (files.length > 0) {
          this.addCopyMenuItems(menu, files, false);
        }
      })
    );
    this.addSettingTab(new VaultFileClipboardSettingTab(this.app, this));
  }
  onunload() {
    console.debug(t("UNLOAD_PLUGIN"));
    if (this.audioCtx) void this.audioCtx.close();
    document.getElementById("vault-file-clipboard-style")?.remove();
    document.removeEventListener("dragstart", this.boundDragStartHandler, true);
    document.removeEventListener("keydown", this.boundKeyDownHandler, true);
  }
  // ──────────────────────────────────────────────
  //  Drag & Drop Handler
  // ──────────────────────────────────────────────
  handleDragStart(evt) {
    if (!evt.altKey) {
      return;
    }
    const target = evt.target;
    if (!target || typeof target.closest !== "function") return;
    const navFile = target.closest(".nav-file-title, .nav-file, .nav-folder-title, .nav-folder");
    if (!navFile) {
      return;
    }
    evt.stopImmediatePropagation();
    const selectedFiles = this.getSelectedFiles();
    let files = [];
    const path2 = navFile.getAttribute("data-path") || navFile.querySelector(".nav-file-title, .nav-folder-title")?.getAttribute("data-path");
    const clickedFile = this.app.vault.getAbstractFileByPath(path2 || "");
    if (clickedFile) {
      if (selectedFiles.length > 1 && selectedFiles.some((f) => f.path === clickedFile.path)) {
        files = selectedFiles;
      } else {
        files = [clickedFile];
      }
    }
    if (files.length > 0) {
      const absolutePaths = files.map((f) => this.getAbsolutePath(f)).filter((p) => p !== null);
      if (absolutePaths.length > 0) {
        this.startNativeDrag(evt, files, absolutePaths);
      }
    }
  }
  startNativeDrag(evt, files, absolutePaths) {
    let nativeDragSuccess = false;
    try {
      const remote = window.require("@electron/remote");
      const wc = remote.getCurrentWebContents();
      if (typeof wc.startDrag === "function") {
        evt.preventDefault();
        evt.stopPropagation();
        let iconImage;
        try {
          const transparent1x1 = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=";
          iconImage = electron.nativeImage.createFromDataURL(transparent1x1);
        } catch {
          iconImage = "";
        }
        if (this.audioCtx?.state === "suspended") {
          void this.audioCtx.resume();
        }
        wc.startDrag({
          file: absolutePaths[0],
          files: absolutePaths,
          // Für neuere Electron-Versionen (Multi-File)
          icon: iconImage
        });
        nativeDragSuccess = true;
        setTimeout(() => this.playSuccessSound(), 500);
      }
    } catch {
      console.debug("Native drag not available, falling back to HTML5 drag");
    }
    if (!nativeDragSuccess) {
      const isWin = os.platform() === "win32";
      evt.dataTransfer?.clearData();
      if (absolutePaths.length === 1) {
        let uri = absolutePaths[0].replace(/\\/g, "/");
        if (isWin && !uri.startsWith("/")) uri = "/" + uri;
        const downloadUrl = `application/octet-stream:${files[0].name}:file://${uri}`;
        evt.dataTransfer?.setData("DownloadURL", downloadUrl);
        evt.dataTransfer?.setData("text/uri-list", `file://${uri}`);
      } else {
        const zipName = `Obsidian_Export_${Date.now()}.zip`;
        const zipPath = path.join(os.tmpdir(), zipName);
        this.createZip(absolutePaths, zipPath);
        let uri = zipPath.replace(/\\/g, "/");
        if (isWin && !uri.startsWith("/")) uri = "/" + uri;
        const downloadUrl = `application/octet-stream:${zipName}:file://${uri}`;
        evt.dataTransfer?.setData("DownloadURL", downloadUrl);
        evt.dataTransfer?.setData("text/uri-list", `file://${uri}`);
      }
      evt.dataTransfer?.setData("text/plain", absolutePaths.join("\n"));
      evt.stopPropagation();
    }
  }
  createZip(sourcePaths, destPath) {
    const platform2 = os.platform();
    try {
      if (platform2 === "darwin") {
        const escapedPaths = sourcePaths.map((p) => `"${p.replace(/"/g, '\\"')}"`).join(" ");
        (0, import_child_process.exec)(`zip -j -q "${destPath}" ${escapedPaths}`, (error) => {
          if (error) console.error("Zip creation failed (Mac):", error);
        });
      } else if (platform2 === "win32") {
        const escapedPaths = sourcePaths.map((p) => `'${p.replace(/'/g, "''")}'`).join(",");
        const script = `powershell.exe -NoProfile -Command "Compress-Archive -Path ${escapedPaths} -DestinationPath '${destPath}' -Force"`;
        (0, import_child_process.exec)(script, (error) => {
          if (error) console.error("Zip creation failed (Win):", error);
        });
      }
    } catch (e) {
      console.error("Failed to execute zip command:", e);
    }
  }
  // ──────────────────────────────────────────────
  //  Hilfsfunktionen
  // ──────────────────────────────────────────────
  addCopyMenuItems(menu, files, isLink = false) {
    const fileCount = files.length;
    const labelSuffix = fileCount > 1 ? ` (${fileCount})` : "";
    const prefix = isLink ? t("LINKED_FILE") : "";
    if (this.settings.showPasteFromClipboardMenu && files.length === 1 && files[0] instanceof import_obsidian.TFolder) {
      menu.addItem((item) => {
        item.setTitle(t("PASTE_FROM_CLIPBOARD")).setIcon("clipboard-paste").setSection("action").onClick(() => void this.pasteExternalFiles(files[0]));
      });
    }
    menu.addItem((item) => {
      const title = `${prefix}${t("COPY_TO_CLIPBOARD")}${labelSuffix}`;
      item.setTitle(title).setIcon("copy").setSection("action").onClick(() => {
        this.copyFilesToClipboard(files);
      });
    });
    if (this.settings.showCopyToTargetFolderMenu) {
      menu.addItem((item) => {
        const title = `${prefix}${t("COPY_TO_TARGET_FOLDER")}${labelSuffix}`;
        item.setTitle(title).setIcon("folder-check").setSection("action").onClick(() => this.copyToTargetFolder(files));
      });
    }
  }
  getSelectedFiles() {
    const files = [];
    const activeEls = document.querySelectorAll(".is-selected, .is-active, .has-active-menu");
    activeEls.forEach((el) => {
      let path2 = el.getAttribute("data-path");
      if (!path2) {
        const childWithPath = el.querySelector("[data-path]");
        if (childWithPath) path2 = childWithPath.getAttribute("data-path");
      }
      if (!path2) {
        const parentWithPath = el.closest("[data-path]");
        if (parentWithPath) path2 = parentWithPath.getAttribute("data-path");
      }
      if (path2) {
        const file = this.app.vault.getAbstractFileByPath(path2);
        if (file && !files.includes(file)) files.push(file);
      }
    });
    return files;
  }
  getSelectedFolderForPaste(target) {
    const folderElement = target?.closest(".nav-folder-title, .nav-folder");
    const focusedFolderPath = folderElement?.getAttribute("data-path") ?? folderElement?.querySelector(".nav-folder-title[data-path]")?.getAttribute("data-path");
    if (focusedFolderPath !== null && focusedFolderPath !== void 0) {
      const focusedFolder = this.app.vault.getAbstractFileByPath(focusedFolderPath);
      if (focusedFolder instanceof import_obsidian.TFolder) return focusedFolder;
    }
    const selectedFolders = this.getSelectedFiles().filter((file) => file instanceof import_obsidian.TFolder);
    return selectedFolders.length === 1 ? selectedFolders[0] : null;
  }
  copyFilesToClipboard(files) {
    const absolutePaths = files.map((f) => this.getAbsolutePath(f)).filter((p) => p !== null);
    if (absolutePaths.length === 0) {
      new import_obsidian.Notice(t("COPY_ERROR_PATHS"));
      return;
    }
    const platform2 = os.platform();
    try {
      if (platform2 === "darwin") {
        const script = `
use framework "Foundation"
use framework "AppKit"
set pb to current application's NSPasteboard's generalPasteboard()
pb's clearContents()
set fileArray to current application's NSMutableArray's array()
${absolutePaths.map((p) => `fileArray's addObject:(current application's NSURL's fileURLWithPath:"${p.replace(/"/g, '\\"')}")`).join("\n")}
pb's writeObjects:fileArray
`;
        const child = (0, import_child_process.exec)("osascript", (error) => {
          if (error) {
            console.error("AppleScript Error:", error);
            clipboard.writeText(absolutePaths.join("\n"));
            new import_obsidian.Notice(t("COPY_ERROR_GENERIC"));
          } else {
            this.playSuccessSound();
            new import_obsidian.Notice(t("COPY_SUCCESS", absolutePaths.length.toString()));
          }
        });
        child.stdin?.write(script);
        child.stdin?.end();
      } else if (platform2 === "win32") {
        const escapedPaths = absolutePaths.map((p) => `'${p.replace(/'/g, "''")}'`).join(", ");
        const script = `powershell.exe -NoProfile -Command "Set-Clipboard -Path ${escapedPaths}"`;
        (0, import_child_process.exec)(script, (error) => {
          if (error) {
            console.error("PowerShell Error:", error);
            clipboard.writeText(absolutePaths.join("\n"));
            new import_obsidian.Notice(t("COPY_ERROR_GENERIC"));
          } else {
            this.playSuccessSound();
            new import_obsidian.Notice(t("COPY_SUCCESS", absolutePaths.length.toString()));
          }
        });
      } else {
        clipboard.writeText(absolutePaths.join("\n"));
        this.playSuccessSound();
        new import_obsidian.Notice(t("COPY_SUCCESS", absolutePaths.length.toString()));
      }
    } catch (err) {
      console.error("Clipboard Error:", err);
      new import_obsidian.Notice(t("CRITICAL_COPY_ERROR"));
    }
  }
  async pasteExternalFiles(targetFolder) {
    const sourcePaths = await this.getFilePathsFromClipboard();
    if (sourcePaths.length === 0) {
      new import_obsidian.Notice(t("PASTE_NO_FILES"));
      return;
    }
    const targetPath = this.getAbsolutePath(targetFolder);
    if (!targetPath) {
      new import_obsidian.Notice(t("COPY_ERROR_PATHS"));
      return;
    }
    let successCount = 0;
    let errorCount = 0;
    for (const sourcePath of sourcePaths) {
      try {
        const sourceStat = fs.statSync(sourcePath);
        const destinationPath = this.getAvailableDestinationPath(targetPath, path.basename(sourcePath));
        const resolvedSource = path.resolve(sourcePath);
        const resolvedDestination = path.resolve(destinationPath);
        if (sourceStat.isDirectory() && (resolvedDestination === resolvedSource || resolvedDestination.startsWith(resolvedSource + path.sep))) {
          throw new Error("Cannot copy a folder into itself.");
        }
        if (sourceStat.isDirectory()) {
          fs.cpSync(sourcePath, destinationPath, { recursive: true, errorOnExist: true });
        } else if (sourceStat.isFile()) {
          fs.copyFileSync(sourcePath, destinationPath, fs.constants.COPYFILE_EXCL);
        } else {
          throw new Error("Unsupported clipboard item type.");
        }
        successCount++;
      } catch (error) {
        console.error(`Paste Error (${sourcePath}):`, error);
        errorCount++;
      }
    }
    if (successCount > 0) {
      this.playSuccessSound();
      new import_obsidian.Notice(t("PASTE_SUCCESS", successCount.toString(), targetFolder.path || "/"));
    }
    if (errorCount > 0) {
      new import_obsidian.Notice(t("PASTE_ERROR", errorCount.toString()));
    }
  }
  getAvailableDestinationPath(targetFolderPath, sourceName) {
    const initialPath = path.join(targetFolderPath, sourceName);
    if (!fs.existsSync(initialPath)) return initialPath;
    const extension = path.extname(sourceName);
    const baseName = extension ? path.basename(sourceName, extension) : sourceName;
    let counter = 1;
    let candidatePath;
    do {
      candidatePath = path.join(targetFolderPath, `${baseName} (${counter})${extension}`);
      counter++;
    } while (fs.existsSync(candidatePath));
    return candidatePath;
  }
  async getFilePathsFromClipboard() {
    let clipboardPaths = [];
    try {
      if (os.platform() === "darwin") {
        clipboardPaths = await this.readMacFileClipboard();
      } else if (os.platform() === "win32") {
        clipboardPaths = await this.readWindowsFileClipboard();
      }
    } catch (error) {
      console.debug("Native file clipboard read failed, using URI fallback:", error);
    }
    if (clipboardPaths.length === 0) {
      const formats = clipboard.availableFormats();
      const uriFormat = formats.find(
        (format) => format.toLowerCase() === "text/uri-list" || format.toLowerCase() === "x-special/gnome-copied-files"
      );
      if (uriFormat) {
        clipboardPaths = this.parseClipboardPathList(clipboard.read(uriFormat));
      }
    }
    return [...new Set(clipboardPaths.map((value) => path.resolve(value)))].filter((value) => fs.existsSync(value));
  }
  readMacFileClipboard() {
    const script = `
ObjC.import('AppKit');
const pasteboard = $.NSPasteboard.generalPasteboard;
const readableClasses = $.NSArray.arrayWithObject($.NSURL);
const readOptions = $.NSDictionary.dictionary;
const urls = pasteboard.readObjectsForClassesOptions(readableClasses, readOptions);
const paths = [];
if (urls) {
    for (let index = 0; index < urls.count; index++) {
        const url = urls.objectAtIndex(index);
        if (url.isFileURL) paths.push(ObjC.unwrap(url.path));
    }
}
JSON.stringify(paths);
`;
    return this.runClipboardCommand("osascript", ["-l", "JavaScript", "-e", script]);
  }
  readWindowsFileClipboard() {
    const script = "@(Get-Clipboard -Format FileDropList | ForEach-Object { $_.FullName }) | ConvertTo-Json -Compress";
    return this.runClipboardCommand("powershell.exe", ["-NoProfile", "-Command", script]);
  }
  runClipboardCommand(command, args) {
    return new Promise((resolve2) => {
      (0, import_child_process.execFile)(command, args, { encoding: "utf8" }, (error, stdout) => {
        if (error || !stdout.trim()) {
          resolve2([]);
          return;
        }
        try {
          const parsed = JSON.parse(stdout.trim());
          if (Array.isArray(parsed)) {
            resolve2(parsed.filter((value) => typeof value === "string"));
          } else if (typeof parsed === "string") {
            resolve2([parsed]);
          } else {
            resolve2([]);
          }
        } catch {
          resolve2(this.parseClipboardPathList(stdout));
        }
      });
    });
  }
  parseClipboardPathList(rawValue) {
    return rawValue.split(/\r?\n/).map((value) => value.trim()).filter((value) => value.length > 0 && value !== "copy" && value !== "cut" && !value.startsWith("#")).map((value) => {
      try {
        return value.startsWith("file://") ? (0, import_url.fileURLToPath)(value) : value;
      } catch {
        return "";
      }
    }).filter((value) => value.length > 0 && path.isAbsolute(value));
  }
  copyToTargetFolder(files) {
    if (!this.settings.targetFolderPath) {
      new import_obsidian.Notice(t("TARGET_FOLDER_NOT_SET"));
      return;
    }
    let successCount = 0;
    let errorCount = 0;
    for (const file of files) {
      const sourcePath = this.getAbsolutePath(file);
      if (!sourcePath) {
        errorCount++;
        continue;
      }
      const destinationPath = path.join(this.settings.targetFolderPath, file.name);
      try {
        if (file instanceof import_obsidian.TFolder) {
          fs.cpSync(sourcePath, destinationPath, { recursive: true });
        } else {
          fs.copyFileSync(sourcePath, destinationPath);
        }
        successCount++;
      } catch (err) {
        console.error(`Copy Error (${file.name}):`, err);
        errorCount++;
      }
    }
    if (successCount > 0) {
      this.playSuccessSound();
      new import_obsidian.Notice(t("TARGET_FOLDER_SUCCESS", successCount.toString()));
    }
    if (errorCount > 0) {
      new import_obsidian.Notice(t("TARGET_FOLDER_ERROR", errorCount.toString()));
    }
  }
  getAbsolutePath(file) {
    const adapter = this.app.vault.adapter;
    if (adapter instanceof import_obsidian.FileSystemAdapter) {
      return adapter.getFullPath(file.path);
    }
    return null;
  }
  initAudio() {
    try {
      this.audioCtx = new (window.AudioContext || window.webkitAudioContext)();
    } catch {
      console.error("AudioContext konnte nicht initialisiert werden");
    }
  }
  playSuccessSound() {
    if (!this.settings.enableAudioFeedback) return;
    if (this.audioCtx?.state === "suspended") {
      void this.audioCtx.resume();
    }
    if (!this.audioCtx) return;
    try {
      const oscillator = this.audioCtx.createOscillator();
      const gainNode = this.audioCtx.createGain();
      oscillator.connect(gainNode);
      gainNode.connect(this.audioCtx.destination);
      oscillator.type = "sine";
      oscillator.frequency.setValueAtTime(600, this.audioCtx.currentTime);
      oscillator.frequency.exponentialRampToValueAtTime(100, this.audioCtx.currentTime + 0.1);
      gainNode.gain.setValueAtTime(0.3, this.audioCtx.currentTime);
      gainNode.gain.exponentialRampToValueAtTime(1e-3, this.audioCtx.currentTime + 0.1);
      oscillator.start();
      oscillator.stop(this.audioCtx.currentTime + 0.1);
    } catch (e) {
      console.error("Audio Feedback Error:", e);
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var VaultFileClipboardSettingTab = class extends import_obsidian.PluginSettingTab {
  plugin;
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName(t("SETTINGS_TITLE")).setHeading();
    new import_obsidian.Setting(containerEl).setName(t("SETTING_CONTEXT_MENU_HEADING")).setHeading();
    new import_obsidian.Setting(containerEl).setName(t("SETTING_PASTE_MENU_NAME")).setDesc(t("SETTING_PASTE_MENU_DESC")).addToggle((toggle) => toggle.setValue(this.plugin.settings.showPasteFromClipboardMenu).onChange(async (value) => {
      this.plugin.settings.showPasteFromClipboardMenu = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName(t("SETTING_TARGET_FOLDER_MENU_NAME")).setDesc(t("SETTING_TARGET_FOLDER_MENU_DESC")).addToggle((toggle) => toggle.setValue(this.plugin.settings.showCopyToTargetFolderMenu).onChange(async (value) => {
      this.plugin.settings.showCopyToTargetFolderMenu = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("hr");
    const isWin = os.platform() === "win32";
    const targetFolderPlaceholder = isWin ? "C:\\path\\to\\folder" : "/path/to/folder";
    new import_obsidian.Setting(containerEl).setName(t("SETTING_TARGET_FOLDER_NAME")).setDesc(t("SETTING_TARGET_FOLDER_DESC")).addText((text) => {
      text.setPlaceholder(targetFolderPlaceholder).setValue(this.plugin.settings.targetFolderPath).onChange(async (value) => {
        this.plugin.settings.targetFolderPath = value.trim();
        await this.plugin.saveSettings();
      });
      return text;
    });
    new import_obsidian.Setting(containerEl).setName(t("SETTING_AUDIO_FEEDBACK_NAME")).setDesc(t("SETTING_AUDIO_FEEDBACK_DESC")).addToggle((toggle) => toggle.setValue(this.plugin.settings.enableAudioFeedback).onChange(async (value) => {
      this.plugin.settings.enableAudioFeedback = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName(t("SETTING_TEST_SOUND_NAME")).setDesc(t("SETTING_TEST_SOUND_DESC")).addButton((btn) => btn.setButtonText(t("SETTING_TEST_SOUND_BUTTON")).onClick(() => {
      this.plugin.playSuccessSound();
    }));
    containerEl.createEl("hr");
    new import_obsidian.Setting(containerEl).setName(t("SETTING_HELP_NAME")).setDesc(t("SETTING_HELP_DESC")).addButton((btn) => btn.setButtonText(t("SETTING_HELP_BUTTON")).onClick(() => {
      window.open("https://github.com/EdgerHao/Obsidian-Natural-Move-Export/tree/codex/vault-file-clipboard");
    })).addButton((btn) => btn.setButtonText(t("SETTING_HELP_BUG_BUTTON")).onClick(() => {
      window.open("https://github.com/EdgerHao/Obsidian-Natural-Move-Export/issues");
    }));
  }
};
